### PR TITLE
Added the link of Codepen implementation of the module in README.md(#6)

### LINKED ISSUE #6: Add the link of Codepen implementation of the module in README.md

### PR DESCRIPTION
**Pull request by Kuljeet-123**
fixes #6 
@plxity here's what the PR offers:

 I have implemented this in Codepen  [here](https://codepen.io/kuljeet-123/pen/zYGWyoY).

- [x] Added link of codepen to the README.md
- [x] Modified Readme

### CODE REVIEW

**Comment by plxity** [comment]
@Kuljeet-123 Add some information in it about the module and add some text too with different color in different themes.

**Comment by Kuljeet-123** [comment]
@plxity  Do I have to change in the codepen code..

**Comment by plxity** [comment]
> @plxity Do I have to change in the codepen code..

Yes

**Comment by Kuljeet-123** [comment]
@plxity  I have updated the codepen code.Please review it.

**Review by plxity — CHANGES_REQUESTED** [review]
Please give the proper margin and padding. Make the UI look better.

**Comment by Kuljeet-123** [comment]
@plxity I have updated the UI of the codepen [here](https://codepen.io/kuljeet-123/pen/zYGWyoY)...Please review it

**Review by plxity — APPROVED** [review]

**Comment by Kuljeet-123** [comment]
@plxity  tysm for your guidance and review.

**Pull request merged**
