### PR TITLE
Updated README.md for better understanding

### PR DESCRIPTION
**Pull request by Kuljeet-123**
Fixes issue:- #3 .

**Changes:-**

  Updated the documentation or README for better understanding.

### CODE REVIEW

**Review by AdityaSrivast — APPROVED** [review]

**Review by yellowwoods12 — APPROVED** [review]

**Review by arpit9667 — CHANGES_REQUESTED** [review]
@Kuljeet-123 I think you skipped the CSS part given in the current version of the Readme.md. You should take a look at that.

**Comment by Kuljeet-123** [comment]
@arpit9667 I have Updated the code.Please review it and merge it.

**Review by yellowwoods12 — APPROVED** [review]

**Review by arpit9667 — APPROVED** [review]

**Review by AdityaSrivast — APPROVED** [review]

**Review by plxity — CHANGES_REQUESTED** [review]
@Kuljeet-123 Code of conduct is not present. Please raise an issue for it. We can't merge this before that file because it is mentioned in the README.md but no file is actually present.

**Comment by Kuljeet-123** [comment]
@plxity I have commented in the issue #19 ...Please assign this to me,So that I can add the link of Code of conduct int README.

**Comment by plxity** [comment]
> @plxity I have commented in the issue #19 ...Please assign this to me,So that I can add the link of Code of conduct int README.

Done :+1:

**Comment by Kuljeet-123** [comment]
@plxity @yellowwoods12 I have Updated the README file.Please review it and merge it also.

**Comment by Kuljeet-123** [comment]
@plxity @yellowwoods12 Please review it .

**Review by plxity — APPROVED** [review]

**Pull request merged**
